apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: java-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - image: cglantschnig/kubernetes-test
        name: java
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080